--- #YAML:1.0
name:               Alien-GSL
version:            0.02
abstract:           Easy installation of the GSL library
author:
    - Joel Berger <joel.a.berger@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    Archive::Extract:  0
    File::Chdir:       0
    LWP::Simple:       0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    parent:  0
resources:
    repository:
        type:  git
        url:   git://github.com:jberger/Alien-GSL.git
        web:   http://github.com/jberger/Alien-GSL
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
