---
abstract: 'Easy installation of the GSL library'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Archive::Extract: 0
  Capture::Tiny: 0
  Carp: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::chdir: 0
  HTTP::Tiny: 0
  Module::Build: 0.38
  Net::FTP: 0
  Scalar::Util: 0
  Sort::Versions: 0
  lib: 0
  parent: 0
  perl: 5.008
configure_requires:
  Archive::Extract: 0
  Capture::Tiny: 0
  Carp: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::chdir: 0
  HTTP::Tiny: 0
  Module::Build: 0.38
  Net::FTP: 0
  Scalar::Util: 0
  Sort::Versions: 0
  lib: 0
  parent: 0
  perl: 5.008
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-GSL
provides:
  Alien::GSL:
    file: lib/Alien/GSL.pm
    version: 0.0305
requires:
  Carp: 0
  File::ShareDir: 1.00
  File::chdir: 0
  List::MoreUtils: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Alien-GSL
version: 0.0305
